name: test package
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
      - devel
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pipenv'
      - name: Install pipenv
        run: pip install pipenv
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - run: pipenv install torch # because torch_scatter contains import torch in the setup.py, we have to install torch first
      - run: pipenv install --dev .
      - run: pipenv run pytest
      # - run: mkdocs gh-deploy --force