name: ci 
on:
  push:
    branches:
      - main
      - devel
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - run: pip install torch # because torch_scatter contains import torch in the setup.py
      - run: pip install -e .[dev]
      - run: pytest
      # - run: mkdocs gh-deploy --force